/*
  Bus de 44 puestos
  num: número de puesto del bus
  staus: free, selected, selecionado, rervado
*/
const dataBus44Seats = [
  {num: '01', status: 'busy'},
  {num: '02', status: 'free'},
  {num: '03', status: 'busy'},
  {num: '04', status: 'busy'},
  {num: '05', status: 'free'},
  {num: '06', status: 'free'},
  {num: '07', status: 'free'},
  {num: '08', status: 'free'},
  {num: '09', status: 'free'},
  {num: '10', status: 'free'},
  {num: '11', status: 'free'},
  {num: '12', status: 'free'},
  {num: '13', status: 'free'},
  {num: '14', status: 'free'},
  {num: '15', status: 'free'},
  {num: '16', status: 'free'},
  {num: '17', status: 'free'},
  {num: '18', status: 'free'},
  {num: '19', status: 'free'},
  {num: '20', status: 'free'},
  {num: '21', status: 'free'},
  {num: '22', status: 'free'},
  {num: '23', status: 'free'},
  {num: '24', status: 'free'},
  {num: '25', status: 'free'},
  {num: '26', status: 'free'},
  {num: '27', status: 'free'},
  {num: '28', status: 'free'},
  {num: '29', status: 'free'},
  {num: '30', status: 'free'},
  {num: '31', status: 'free'},
  {num: '32', status: 'free'},
  {num: '33', status: 'free'},
  {num: '34', status: 'free'},
  {num: '35', status: 'free'},
  {num: '36', status: 'free'},
  {num: '37', status: 'free'},
  {num: '38', status: 'free'},
  {num: '39', status: 'free'},
  {num: '40', status: 'free'},
  {num: '41', status: 'free'},
  {num: '42', status: 'free'},
  {num: '43', status: 'free'},
  {num: '44', status: 'free'}//,
  //{num: '45', status: 'free'},
  //{num: '46', status: 'free'},
  //{num: '47', status: 'free'},
  //{num: '48', status: 'free'},
  //{num: '49', status: 'free'},
  //{num: '50', status: 'free'},
  //{num: '51', status: 'free'},
  //{num: '52', status: 'free'},
  //{num: '53', status: 'free'},
  //{num: '54', status: 'free'}
]
const dataBus57Seats = [
  {num: '01', status: 'busy'},
  {num: '02', status: 'free'},
  {num: '03', status: 'busy'},
  {num: '04', status: 'busy'},
  {num: '05', status: 'free'},
  {num: '06', status: 'free'},
  {num: '07', status: 'free'},
  {num: '08', status: 'free'},
  {num: '09', status: 'free'},
  {num: '10', status: 'free'},
  {num: '11', status: 'free'},
  {num: '12', status: 'free'},
  {num: '13', status: 'free'},
  {num: '14', status: 'free'},
  {num: '15', status: 'free'},
  {num: '16', status: 'free'},
  {num: '17', status: 'free'},
  {num: '18', status: 'free'},
  {num: '19', status: 'free'},
  {num: '20', status: 'free'},
  {num: '21', status: 'free'},
  {num: '22', status: 'free'},
  {num: '23', status: 'free'},
  {num: '24', status: 'free'},
  {num: '25', status: 'free'},
  {num: '26', status: 'free'},
  {num: '27', status: 'free'},
  {num: '28', status: 'free'},
  {num: '29', status: 'free'},
  {num: '30', status: 'free'},
  {num: '31', status: 'free'},
  {num: '32', status: 'free'},
  {num: '33', status: 'free'},
  {num: '34', status: 'free'},
  {num: '35', status: 'free'},
  {num: '36', status: 'free'},
  {num: '37', status: 'free'},
  {num: '38', status: 'free'},
  {num: '39', status: 'free'},
  {num: '40', status: 'free'},
  {num: '41', status: 'free'},
  {num: '42', status: 'free'},
  {num: '43', status: 'free'},
  {num: '44', status: 'free'},
  {num: '45', status: 'free'},
  {num: '46', status: 'free'},
  {num: '47', status: 'free'},
  {num: '48', status: 'free'},
  {num: '49', status: 'free'},
  {num: '50', status: 'free'},
  {num: '51', status: 'free'},
  {num: '52', status: 'free'},
  {num: '53', status: 'free'},
  {num: '54', status: 'free'},
  {num: '55', status: 'free'},
  {num: '56', status: 'free'},
  {num: '57', status: 'free'},
]
const dataBusNilahue46 = [
  {num: '01', status: 'busy'},
  {num: '02', status: 'free'},
  {num: '03', status: 'busy'},
  {num: '04', status: 'busy'},
  {num: '05', status: 'free'},
  {num: '06', status: 'free'},
  {num: '07', status: 'free'},
  {num: '08', status: 'free'},
  {num: '09', status: 'free'},
  {num: '10', status: 'free'},
  {num: '11', status: 'free'},
  {num: '12', status: 'free'},
  {num: '13', status: 'free'},
  {num: '14', status: 'free'},
  {num: '15', status: 'free'},
  {num: '16', status: 'free'},
  {num: '17', status: 'free'},
  {num: '18', status: 'free'},
  {num: '19', status: 'free'},
  {num: '20', status: 'free'},
  {num: '21', status: 'free'},
  {num: '22', status: 'free'},
  {num: '23', status: 'free'},
  {num: '24', status: 'free'},
  {num: '25', status: 'free'},
  {num: '26', status: 'free'},
  {num: '27', status: 'free'},
  {num: '28', status: 'free'},
  {num: '29', status: 'free'},
  {num: '30', status: 'free'},
  {num: '31', status: 'free'},
  {num: '32', status: 'free'},
  {num: '33', status: 'free'},
  {num: '34', status: 'free'},
  {num: '35', status: 'free'},
  {num: '36', status: 'free'},
  {num: '37', status: 'free'},
  {num: '38', status: 'free'},
  {num: '39', status: 'free'},
  {num: '40', status: 'free'},
  {num: '41', status: 'free'},
  {num: '42', status: 'free'},
  {num: '43', status: 'free'},
  {num: '44', status: 'free'},
  {num: '45', status: 'free'},
  {num: '46', status: 'free'},
]
const dataRut = [
  {rut01: '12.534.664-5'},
  {rut02: '24.346.646-6'},
  {rut03: '16.548.684-5'},
  {rut04: '17.549.964-0'}
]
const dataCityCountry = [
  'Antofagasta, Chile',
  'Arica, Chile',
  'Baquedano, Chile',
  'Concepción, Chile',
  'Curicó, Chile',
  'Diego de Almagro, Chile',
  'Guanaqueros, Chile',
  'Hualpín, Chile',
  'Illapel, Chile',
  'Santiago, Chile'
]
// Delete city from array
var  dataCityDestination = function (data, pera){
  return  data.filter( (value) => value !== pera );
}
export {
  dataBus44Seats,
  dataBus57Seats,
  dataRut,
  dataCityCountry,
  dataBusNilahue46,
  dataCityDestination,
}
